name: Build And Push Image To ACR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  BuildAndPushImageToACR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.HUB_CREDENTIALS }}

      - name: ACR login
        run: |
          az acr login --name ${{ vars.ACR_NAME }}

      - name: Build and Push
        run: |
          docker build -t ${{ vars.ACR_NAME }}.azurecr.io/terraform/terraform-image:${{ github.sha }} -f Dockerfile . && \
          docker push ${{ vars.ACR_NAME }}.azurecr.io/terraform/terraform-image:${{ github.sha }}