name: ACR Login Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ vars.SPOKE_DEV_CLIENT_ID }}",
              "clientSecret": "${{ secrets.SPOKE_DEV_CLIENT_SECRET }}",
              "subscriptionId": "${{ vars.SPOKE_DEV_SUBSCRIPTION_ID }}",
              "tenantId": "${{ vars.TENANT_ID }}"
            }

      - name: ACR Login
        run: |
          az acr login --name acrhubcus01