name: ACR Login Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SPOKE_DEV_CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SPOKE_DEV_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: |
          az acr login --name acrhubcus01