name: Build And Push Docker Image To ACR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  BuildAndPushDockerImageToACR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.HUB_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: ACR login
        run: |
          az acr login --name acrhubdevscuslzic

      - name: Build And Push
        run: |
          docker build -t acrhubdevscuslzic.azurecr.io/terraform/terraform-image:latest -f Dockerfile . && \
          docker push acrhubdevscuslzic.azurecr.io/terraform/terraform-image:latest